volumes:
  grafana_data:
  mongo_data:

networks:
  cyberpot_net:

services:
  mongo:
    image: mongo:6
    container_name: cyberpot-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - cyberpot_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cyberpot-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - cyberpot_net
    depends_on:
      - mongo

  honeypot:
    image: cowrie/cowrie
    container_name: cyberpot-honeypot
    restart: unless-stopped
    ports:
      - "22:2222"
    environment:
      - COWRIE_TELNET_ENABLED=no
      - COWRIE_SSH_ENABLED=yes
    volumes:
      - ./cowrie/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./cowrie/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
    networks:
      - cyberpot_net
    depends_on:
      - mongo

  grafana:
    image: grafana/grafana:latest
    container_name: cyberpot-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - cyberpot_net
    depends_on:
      - backend
      - mongo
